# Generated by Django 5.2.17 on 2026-08-09 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.CharField(max_length=200, unique=True, verbose_name="адрес"),
                ),
                ("lat", models.FloatField(verbose_name="широта")),
                ("lon", models.FloatField(verbose_name="долгота")),
                (
                    "requested_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="дата запроса к геокодеру"
                    ),
                ),
            ],
            options={
                "verbose_name": "место",
                "verbose_name_plural": "места",
            },
        ),
    ]
