# Generated by Django 5.2.17 on 2026-08-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geocoding", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="lat",
            field=models.FloatField(blank=True, null=True, verbose_name="широта"),
        ),
        migrations.AlterField(
            model_name="place",
            name="lon",
            field=models.FloatField(blank=True, null=True, verbose_name="долгота"),
        ),
    ]
