# Generated by Django 5.2.17 on 2026-08-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0040_fill_orderitem_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("unprocessed", "Необработан"),
                    ("cooking", "Готовится"),
                    ("delivering", "Доставляется"),
                    ("completed", "Выполнен"),
                ],
                db_index=True,
                default="unprocessed",
                max_length=20,
                verbose_name="статус",
            ),
        ),
    ]
