# Generated by Django 5.2.17 on 2026-08-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0043_order_called_at_order_delivered_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Наличностью при доставке"),
                    ("electronic", "Электронно"),
                ],
                db_index=True,
                default="cash",
                max_length=20,
                verbose_name="способ оплаты",
            ),
        ),
    ]
