# Generated by Django 5.2.17 on 2026-08-09 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0044_order_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="foodcartapp.restaurant",
                verbose_name="ресторан-исполнитель",
            ),
        ),
    ]
