# Generated by Django 5.2.17 on 2026-08-09 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0045_order_restaurant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.CharField(max_length=200, verbose_name="адрес"),
        ),
    ]
