# Generated by Django 5.2.17 on 2026-08-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0046_alter_order_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Наличностью при доставке"),
                    ("electronic", "Электронно"),
                ],
                db_index=True,
                max_length=20,
                verbose_name="способ оплаты",
            ),
        ),
    ]
